# Generated by Django 4.0.1 on 2022-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=70)),
                ('book_desc', models.TextField()),
            ],
        ),
    ]
